
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDEAND BOOLEAN_KW BOOL_KW CHARACTER_KW CHAR_KW CLOSING_BRACE CLOSING_BRACKET CLOSING_PARENTHESES COLON COMEBACK_KW COMMENT CONST_KW CONTINUE_KW DIVIDE DIVIDEEQUAL DOT DOUBLE_DOT ELSE_KW EQUAL EQUALEQUAL FALSE_KW GIVEBACK_KW GREATEREQUAL GREATER_THAN ID IF_KW INTEGER_KW INT_KW LESSEQUAL LESS_THAN LOGINCAL_AND LOGINCAL_OR MINUS MINUSEQUAL MINUSMINUS NOTEQUAL NUMBER OPENING_BRACE OPENING_BRACKET OPENING_PARENTHESES OR OTHER_KW PERCENTAGE PLUS PLUSEQUAL PLUSPLUS QUESTION_MARK SEMICOLON STATIC_KW THEN_KW TILDA TILL_KW TIMES TIMESEQUAL TRUE_KW VOID_KWexpr : expr PLUS exprexpr : expr MINUS exprexpr : expr TIMES expr\n                | expr DIVIDE exprexpr : NUMBERexpr : OPENING_PARENTHESES expr CLOSING_PARENTHESES'
    
_lr_action_items = {'NUMBER':([0,3,4,5,6,7,],[1,1,1,1,1,1,]),'MINUS':([1,2,8,9,10,11,12,13,],[-5,6,6,-3,-1,-2,-4,-6,]),'TIMES':([1,2,8,9,10,11,12,13,],[-5,4,4,-3,4,4,-4,-6,]),'DIVIDE':([1,2,8,9,10,11,12,13,],[-5,7,7,-3,7,7,-4,-6,]),'$end':([1,2,9,10,11,12,13,],[-5,0,-3,-1,-2,-4,-6,]),'OPENING_PARENTHESES':([0,3,4,5,6,7,],[3,3,3,3,3,3,]),'PLUS':([1,2,8,9,10,11,12,13,],[-5,5,5,-3,-1,-2,-4,-6,]),'CLOSING_PARENTHESES':([1,8,9,10,11,12,13,],[-5,13,-3,-1,-2,-4,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,3,4,5,6,7,],[2,8,9,10,11,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr PLUS expr','expr',3,'p_add','yacc.py',24),
  ('expr -> expr MINUS expr','expr',3,'p_sub','yacc.py',28),
  ('expr -> expr TIMES expr','expr',3,'p_mult_div','yacc.py',33),
  ('expr -> expr DIVIDE expr','expr',3,'p_mult_div','yacc.py',34),
  ('expr -> NUMBER','expr',1,'p_expr2NUM','yacc.py',45),
  ('expr -> OPENING_PARENTHESES expr CLOSING_PARENTHESES','expr',3,'p_parens','yacc.py',49),
]
